name: deepTCR
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python==3.7.6
  - tensorflow-gpu==2.1.0
  - tensorboard==2.1.0
  - cudatoolkit==10.1.243
  - cudnn==7.6.5
  - h5py==2.10.0
  - hdf5==1.10.4
  - biopython==1.76
  - ipykernel
  - joblib==0.14.1
  - matplotlib==3.1.3
  - numpy==1.18.1
  - pandas==1.0.1
  - pillow==7.0.0
  - pyteomics==4.2
  - pytest==5.3.5
  - scikit-learn==0.22.1
  - scipy==1.5.0
  - tqdm==4.42.1
  - requests==2.22.0
  - requests-futures==1.0.0
  - seaborn==0.10.0
  - python-Levenshtein==0.12.0
  - pip==20.0.2
  - pip:
    - "--editable ."
