name: deepTCR
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - tensorflow-gpu=1.12
  - cudatoolkit==9.2
  - cudnn==7.6.4
  - tensorboard=1.12
  - biopython==1.74
  - ipython
  - ipykernel
  - joblib==0.14.0
  - keras==2.2.4
  - keras-applications==1.0.8
  - keras-preprocessing==1.1.0
  - matplotlib==3.1.1
  - numpy==1.17.3
  - pandas==0.25.2
  - pillow==6.2.1
  - pyteomics==4.1
  - pytest==5.2.2
  - scikit-learn==0.21.3
  - scipy==1.3.1
  - statsmodels==0.10.1
  - tqdm==4.36.1
  - requests==2.22.0
  - requests-futures==1.0.0
  - seaborn=0.9.0
  - pip==19.3.1
  - pip:
#    - keract # installing this updates keras to a higher version...
    - keras-metrics==1.1.0
    - "--editable ."
